const { User } = require("../models");

module.exports = async () => {
  const users = [
    {
      firstname: "Lucía",
      lastname: "García",
      email: "lucia.garcia@gmail.com",
      password: "1234",
      address: "Calle del Sol 28",
      phone: "091654349",
      avatar: "Profile_defaultFemale1.png",
    },
    {
      firstname: "Santiago",
      lastname: "Fernández",
      email: "santiago.fernandez@gmail.com",
      password: "1234",
      address: "Calle de la Paz 15",
      phone: "091654349",
      avatar: "Profile_defaultMale1.png",
    },
    {
      firstname: "María",
      lastname: "Martínez",
      email: "maria.martinez@gmail.com",
      password: "1234",
      address: "Avenida de la Libertad 5",
      phone: "091654349",
      avatar: "Profile_defaultFemale2.png",
    },
    {
      firstname: "Adrián",
      lastname: "Gómez",
      email: "adrian.gomez@gmail.com",
      password: "1234",
      address: "Plaza Mayor 10",
      phone: "091654349",
      avatar: "Profile_defaultMale2.png",
    },
    {
      firstname: "Andrea",
      lastname: "Hernández",
      email: "andrea.hernandez@gmail.com",
      password: "1234",
      address: "Calle del Cid 3",
      phone: "091654349",
      avatar: "Profile_defaultFemale3.png",
    },
    {
      firstname: "David",
      lastname: "Pérez",
      email: "david.perez@gmail.com",
      password: "1234",
      address: "Calle de la Estrella 12",
      phone: "091654349",
      avatar: "Profile_defaultMale3.png",
    },
    {
      firstname: "Alicia",
      lastname: "González",
      email: "alicia.gonzalez@gmail.com",
      password: "1234",
      address: "Avenida de la Constitución 8",
      phone: "091654349",
      avatar: "Profile_defaultFemale4.png",
    },
    {
      firstname: "Jorge",
      lastname: "Rodríguez",
      email: "jorge.rodriguez@gmail.com",
      password: "1234",
      address: "Calle Mayor 20",
      phone: "091654349",
      avatar: "Profile_defaultMale4.png",
    },
    {
      firstname: "Ana",
      lastname: "Sánchez",
      email: "ana.sanchez@gmail.com",
      password: "1234",
      address: "Calle de la Luna 14",
      phone: "091654349",
      avatar: "Profile_defaultFemale5.png",
    },
    {
      firstname: "Carlos",
      lastname: "López",
      email: "carlos.lopez@gmail.com",
      password: "1234",
      address: "Calle del Sol 16",
      phone: "091654349",
      avatar: "Profile_defaultMale5.png",
    },
    {
      firstname: "Elena",
      lastname: "Giménez",
      email: "elena.gimenez@gmail.com",
      password: "1234",
      address: "Calle de la Playa 9",
      phone: "091654349",
      avatar: "Profile_defaultFemale6.png",
    },
    {
      firstname: "Juan",
      lastname: "Pérez",
      email: "user@1234.com",
      password: "1234",
      address: "Avenida del Mar 23",
      phone: "091654349",
      avatar: "Profile_defaultUser.png",
    },
  ];

  await User.bulkCreate(users);
  console.log("[Database] Se corrió el seeder de Users.");
};
